### ISSUE TITLE
CORS Support

### ISSUE THREAD

**Issue by stevendearborn** [julianvilas/docker-http-server#1]
I like the simplicity of using http-server, especially since it is a Node app.

I need the same to support CORS, for example, using http-server natively, I can do the following:
http-server /workspace/webfiles -p 9090 --cors=Authorization,Accept,Accept-Language,Content-Type,Content-Language,API_Key -a 127.0.0.1

Of course, I could use nginx docker image to serve up the same files, but I would still need to configure CORS for it.

I would like a Docker image for this that supported the configuration of CORS, but I am learning Docker.  If you have any suggestions, please let me know.  Thank you.

**Comment by stevendearborn** [comment]
I made an easy change and built a new image:
CMD [ "http-server", "/Users", "--cors=Authorization,Accept,Accept-Language,Content-Type,Content-Language,API_Key" ]

/Users is the root directory of the volume that is shared between the host and the container.  The volume that is used is a Managed Volume and not a Bind Mount one.  I would like it to be a Bind Mount; do you have a recommendation as to how to change while keeping the separation integrity between the Docker container and the web site files to be served? Yes, I am serving up Swagger API definitions as files.

**Comment by stevendearborn** [comment]
I figured out how to do the Bind Mount I wanted with only changing the http-server parameters.

**Comment by julianvilas** [comment]
Hi @stevendearborn,

Sorry for the late response. Happy to see that you already solved the issue :)

Thanks for the updates!
